### ISSUE TITLE
Roadmap/To do

### ISSUE THREAD

**Issue by rdshft** [redshifttt/discordbot#2]
Creating this issue as a way to highlight what needs to be implemented and with priority.

## High Priority

- [ ] Haskell rewrite #1 
- [ ] Nix flake
- [ ] Hercules-CI

### Commands

- [ ] Turning the `./guild` and `./userinfo` commands into a single dual-wielding `./info` command that has its own sub-commands for the respective guild and user information.
- [ ] Guild statistics within the info command
- [ ] 8ball
- [ ] YouTube
- [ ] Image Search

### Systems

- [ ] Guild statistics gathering (just counters)

### Misc

- [ ] Having a better way to document commands

This will change as the project progresses.
